services:
  - type: web
    name: silentedgechainbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: true
      - key: PORT
        sync: true
      - key: RISK_MODE
        sync: true
      - key: ENVIRONMENT
        sync: true
    autoDeploy: true
